source 'https://rubygems.org'

gem 'builder', '~> 3.2'
gem 'faraday', '~> 2.3'
gem 'json', '~> 2.6'
gem 'middleman', '~> 4.4'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-blog', '~> 4.0'
gem 'middleman-minify-html', '~> 3.4'
gem 'middleman-search_engine_sitemap', '~> 1.4'
gem 'nokogiri', '~> 1.13'
gem 'psych', '< 4.0'
gem 'redcarpet', '~> 3.5'
gem 'slim', '~> 4.1'
gem 'webrick', '~> 1.7'
